### PR TITLE
Use latest stanford-mods gem with new location field

### PR DESCRIPTION
**Pull request by peetucket**
@ndushay

### CODE REVIEW

**Comment by ndushay** [comment]
:+1: LGTM

**Comment by ndushay** [comment]
would you be willing to do THIS gem's version bump as a separate PR so it is easy to spot in the commit history?  Or, do THIS gem's version bump directly to master - that is the ONLY code change I'm ok with directly to master.

**Comment by peetucket** [comment]
removed version bump

**Comment by ndushay** [comment]
:+1:  for you to merge yourself after builds pass.

**Pull request merged**
